# Generated by Django 6.0.3 on 2026-05-07 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('handle', models.CharField(blank=True, max_length=30, unique=True)),
                ('bio', models.CharField(blank=True, max_length=150)),
                ('avatar', models.TextField(blank=True)),
                ('cover', models.TextField(blank=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
